- index.js
- package.json
- test.js
> Wait for all files to be completed before calling the handler.

- .editorconfig
- .travis.yml
- index.d.ts
- package.json
- test/multipart.test.js
- test/types/index.ts
- test/types/tsconfig.json
Motivation: [see here](https://github.com/fastify/fastify-static/issues/66#issuecomment-460159590)
This PR adds a modified version of my typings on DefinitelyTyped to the org repo as that seems to be the consensus now.
> feat: add typings to org repo

- index.d.ts
The `multipart` method of `FastifyRequest` has 3 parameters, but the third parameter `options` is missing in the type definition file.
> Update type definition to align with JavaScript implementation

- index.d.ts
- test/types/index.ts
As discussed in the issue, changing the default export. Also removing the export that isn't compatible with this format.
I also changed the test to make the server start so you can verify that it works by running something like `ts-node test/types/index.ts`.
> Fix default export to commonjs export. Fixes #76.

- README.md
- index.js
- test/append-body.test.js
I was having issues with the test "should call finished when both files are pumped" locally but had no changes to affect it. Seems the check on filesCount happens before the callback in pump() is getting executed.
> #102 - Dont attach file to body if the limit has been reached

- index.js
- package.json
- test/append-body.test.js
- test/multipart.test.js
> Explicit handle __proto__ fields.

- README.md
- examples/example.js
> fix docs examples

- README.md
- examples/example.js
- index.js
- test/multipart.test.js
> Rename multipartIterator to parts

- index.js
- test/multipart-attach-body.test.js
> Add a check if request is multipart on the preValidation hook when `attachFieldsToBody` is true.

- test/multipart-attach-body.test.js
> refactored multipart attach body test

- README.md
- index.js
- test/multipart-big-stream.test.js
- test/multipart-disk.test.js
- test/multipart-small-stream.test.js
- test/multipart-stream.test.js
> rethrow busboy error when storing files on disk, add tests

- index.js
- test/multipart.test.js
This is to fix one issue that I found in my project, not sure whether this behaviour is intended or not.
Basically, I found that in some cases, it's possible that onField of busyboy will be trigger multiple times before user read the parsed lastValue, this will cause some field in formdata are missing.
> fix issue that in multipart handler might miss fields

- index.d.ts
- test/index.test-d.ts
Allow user to declare a field as a non-file value with a generic
`Multipart<T>` to set the correct type of the value.
Closes #162
> Add correct type for non-file value

- index.js
PASS  test/multipart-big-stream.test.js 3 OK 254.126ms
PASS  test/multipart-concat.test.js 9 OK 256.44ms
PASS  test/legacy/multipart.test.js 43 OK 446.868ms
PASS  test/multipart-body-schema.test.js 8 OK 374.937ms
PASS  test/multipart-attach-body.test.js 16 OK 312.564ms
PASS  test/legacy/append-body.test.js 74 OK 1s
PASS  test/multipart-disk.test.js 42 OK 527.466ms
PASS  test/multipart-security.test.js 8 OK 283.763ms
PASS  test/multipart-small-stream.test.js 2 OK 141.19ms
PASS  test/multipart.test.js 68 OK 459.869ms
PASS  test/big.test.js 9 OK 9s
PASS  test/legacy/big.test.js 12 OK 12s
🌈 SUMMARY RESULTS 🌈
Suites:   12 passed, 12 of 12 completed
Asserts:  294 passed, of 294
Time:     17s …
> only add requestFile to tmpUploads if it is not rejected by busboy

- index.js
- test/big.test.js
- test/legacy/append-body.test.js
- test/legacy/big.test.js
- test/legacy/multipart.test.js
- test/multipart-big-stream.test.js
- test/multipart-disk.test.js
- test/multipart.test.js
- tester.js
> fix: lint errors

- index.js
- test/multipart-disk.test.js
Fixes https://github.com/fastify/fastify-multipart/issues/185
- Implemented the solution suggested in https://github.com/fastify/fastify-multipart/issues/185#issuecomment-726197792
- Added coverage for the same
Note: We might not need this when https://github.com/mscdex/busboy/pull/237/files gets merged.
> fix(185): saveRequestFiles works with large file

- README.md
- index.d.ts
- index.js
- package.json
- test/big.test.js
- test/index.test-d.ts
- test/multipart.test.js
This PR resolve #196 by adding a new option `throwFileSizeLimit`.
The option can be configure in two way:
```JS
fastify.register(fastifyMultipart, { throwFileSizeLimit: false })
```
```JS
const file = await req.file({ throwFileSizeLimit: false, limits: { fileSize: 17000 } })
const files = await req.files({ throwFileSizeLimit: false, limits: { fileSize: 17000 } })
const parts = await req.parts({ throwFileSizeLimit: false, limits: { fileSize: 17000 } })
```
> fix: file size limit

- .github/workflows/ci.yml
To distinguish them, otherwise they're all called Node {something}
> chore: include os name in build name

- index.js
- test/multipart-small-stream.test.js
Feature proposal:
Allow req.file to throw an error when the file is bigger than the limit
closes #196 
> feat: req.file throws filesize error

- index.js
- test/multipart.test.js
- move throwFileSizeLimit declaration to its original place
> Fix test failures

- index.d.ts
- test/index.test-d.ts
Make it possible to provide busboy options without having to include tmpdir when calling saveRequestFiles in TypeScript.
> fix(types): saveRequestFiles option types

- index.js
- test/legacy/multipart.test.js
Cover the case when one of the streams gets closed prematurely after Fastify had received it.
> Test calling finished if one of the streams closes prematurely

- index.d.ts
- test/index.test-d.ts
Resolve: #201
As changing the function itself will break most of ppl using this plugin. I am +1 on changing the type definition to resolve the issue mention above.
> fix: typings onFile

- README.md
The pull request add documentation on how to consume `req.body` in key-value pairs.
This may help new comers from Express.js
> docs: consume req.body in the form of key-value pairs

- .github/workflows/ci.yml
- index.js
Closes #232 
The code change required to support Node 16 is one that took a while to figure out. 
These are the symptoms:
- a file sent in the request is larger than the default write stream highWaterMark (16k)
- the user is saving the file to the file system with the decorator `req.saveRequestFiles()`
- the plugin hangs in the async iterators used to loop through the files using a producer/consumer pattern
The reason for this is that the Busboy `finish` event is not emitted, which is breaking the producer/consumer pattern implemented in the plugin.
After much experimentation I traced back the root cause to the `cleanup` function of the plugin which unsubscribes from all Busboy events. My speculation is that something has changed in Node 16 streams which causes such cleanup function, …
> ci: add Node 16

- README.md
- examples/example.js
- test/index.test-d.ts
- test/multipart.test.js
This pull request remove unnecessary await keyword from documentations.
Related: https://github.com/fastify/fastify-multipart/pull/233#issuecomment-841374036, https://github.com/fastify/fastify-multipart/pull/233#issuecomment-841638187
> Remove unnecessary await keywords from documentations, tests and examples

- index.d.ts
- test/index.test-d.ts
fixes #247
Current type is based on incorrect busBoy typings which will be addressed separately. In reality `Readable` is actually provided.
> Fix file stream type

- README.md
Updates the example to work with `limits.fileSize` option.
Closes #256, Closes #250 
> Updates fileSize limits example in README

- README.md
This PR adds a small note to documentation about zero bytes files when assigning all fields to body.
Closes #200
> docs: add note about zero bytes file on attaching fields to body

- README.md
- index.js
- test/multipart-fileLimit.test.js
Ref https://github.com/fastify/fastify-multipart/issues/263
> feat breaking: throw file size limit on toBuffer calls

- README.md
- index.d.ts
This method was removed in https://github.com/fastify/fastify-multipart/pull/147 but is still mentioned in docs and (which is more of a problem) in types.
> fix: remove multipartIterator from types and docs

- README.md
Updated the README with additional (missing) information that is relevant for `sharedSchemaId`. 
Closes: https://github.com/fastify/fastify-multipart/issues/276, closes https://github.com/fastify/fastify-multipart/issues/277
> Updated README.md with relevant information about the sharedSchemaId

- README.md
- index.js
- package.json
- test/multipart-json.test.js
- test/multipart.json.test.js
> feat: Parse JSON fields when content-type is set. Fixes #278.

- index.d.ts
- index.js
- package.json
- test/index.test-d.ts
This replaces unsupported original version of `busboy` with our own fork, sporting the holy trifecta of security fixes, performance improvements, and a richer feature-set.
It is a semver minor change with no known breaking changes.
fixes #297
> Migrate to @fastify/busboy

- README.md
Hello.
Following https://github.com/fastify/fastify-multipart/pull/300, this PR aims to :
- update the documentation references to `@fastify/busboy` instead of `busboy`
- remove the installation step of `@types/busboy` (`@fastify/busboy` has its own types definitions)
> docs: from `busboy` to `@fastify/busboy`

- index.d.ts
- test/index.test-d.ts
> Fix TS types

- index.d.ts
- test/index.test-d.ts
By changing the type of `MultipartFile#file` to `BusboyFileStream`, accessing the `truncated` property no longer raises a TypeScript error.
> Change `MultipartFile#file` type to `BusboyFileStream`

- index.js
- package.json
- test/multipart-incomplete-upload.test.js
If the client cancels the http request (e.g. just closes the socket),
the underlying file stream will not be closed with an error but
the request handling will hang.
The tests saves the stream of a file part into a Noop write stream
through pipeline. If the client cancels the request, the pipeline
call will not return. With the fix, we keep track of the file that
is currently being processed and in the case of an error event on the
node request, this file will be destroyed.
This addresses #315 and makes https://github.com/fastify/busboy/pull/81 superflous.
> feat: added destroying of part.file if the node request ends with an error event

- README.md
> docs: move data.fields line in README

- test/big.test.js
- test/legacy/big.test.js
- test/multipart-big-stream.test.js
- test/multipart-disk.test.js
- tester.js
This PR fixes a typo.
`octect` -> `octet`
> chore: fix typo octect -> octet

- README.md
- index.d.ts
- index.js
- test/multipart-attach-body.test.js
Adds an option `attachFieldsToBody: 'valueOnly'`. When this is option is enabled, the field values are attached to the body directly, similar to what is described in the readme:
```js
const body = Object.fromEntries(
Object.keys(req.body).map((key) => [key, req.body[key].value])
) // Request body in key-value pairs, like req.body in Express
```
This would be a convenient feature to include so that json-schemas can be shared more easily between the content types `application/json`, `application/x-www-form-urlencoded`, and `multipart/form-data`. 
Without this capability, this needs to be performed in awkward route handler transforms, e.g.:
```ts
fastify.post<{ Body: ServiceAuthRequest, Reply: ServiceAuthResponse }>('/request_key', {
preValidation: (request, _reply, done) => {
if …
```
> Option to attach to body as key-value pairs

- .npmrc
> add .npmrc with package-lock=false to disable package-lock.json generation

- README.md
- callback.md
- examples/example-legacy-validation.js
- examples/example-legacy.js
- examples/example-validation.js
- examples/example.js
> chore: replace use of deprecated variadic `listen()`

- index.js
- test/multipart-fileLimit.test.js
closes #383
increase coverage #202:
```
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |     100 |    96.85 |     100 |     100 |                   
index.js |     100 |    96.85 |     100 |     100 | 163,247-254,551   
----------|---------|----------|---------|---------|-------------------
```
benefit #378:
from https://nodejs.org/api/stream.html#readablesymbolasynciterator
> If the loop terminates with a break, return, or a throw, the stream will be destroyed
> fix: manage big file uploads

- index.d.ts
- test/index.test-d.ts
I've tried to correct the types by analyzing the source code and busboy's type definitions.
Fixes #251
> Improve typescript types

- index.d.ts
- index.js
- test/multipart-json.test.js
Include the content-type even if it's not JSON.
> Always include form value's content-type

- index.js
throwFileSizeLimit should not be overwritten.
> dont overwrite throwFileSizeLimit

- index.js
> move createError-calls out of function

- index.js
- test/fix-313.test.js
Added files async files generator function to `saveRequestFiles` which fetches files from body instead of from `getMultipartFiles` when `attachFieldsToBody is set to true
Partially addresses #313
> Support for saveRequestFiles with attachFieldsToBody set true

- test/multipart-security.test.js
- test/multipart.test.js
Signed-off-by: Matteo Collina <hello@matteocollina.com>
> Fix flaky test on windows

- index.js
- test/multipart-empty-body.test.js
> fix: empty bodies does not crash anymore

- README.md
- examples/example.js
- index.d.ts
- index.js
- test/big.test.js
- test/fix-313.test.js
- test/index.test-d.ts
- test/multipart-body-schema.test.js
- test/multipart.test.js
Easier type narrowing as discussed #144
> feat: part.type for easy type narrowing

- README.md
- index.d.ts
- index.js
- test/multipart-attach-body.test.js
Gives access to original request via `this` on `onFile` function. This should be useful to link file handler with original request or create unique IDs based on request id.
Fixes #427
> Bind original request to `onFile` function `this`

- index.d.ts
- index.js
- test/multipart-duplicate-save-request-file.test.js
In cases where multiple hooks and the handler needs to use the saved request files, and they cannot share the first call's result of `saveRequestFile`, they would call it twice or more which would result into piping the same file to disk more than once. As we can check by the following code:
```ts
fastify.post('/', async (req, rep) => {
await req.saveRequestFiles() // [{ filepath: '/tmp/0388009396720a01.txt' }]
await req.saveRequestFiles() // [{ filepath: '/tmp/0388009396720a02.txt' }]
await req.saveRequestFiles() // [{ filepath: '/tmp/0388009396720a03.txt' }]
})
```
Now, `saveRequestFiles` will use the same system file and do not write the disk more than needed.
```ts
fastify.post('/', async (req, rep) => {
await req.saveRequestFiles() // [{ filepath: '/tmp/0388009396720a04.txt' }]
await …
```
> Avoid piping the same file multiple times in case `saveRequestFile` is called twice.

- README.md
- examples/example-with-swagger.js
- index.d.ts
- index.js
- package.json
- test/avj-plugin.test-d.ts
- test/multipart-ajv-file.test.js
Previously, there was only one example on how to use `@fastify/multipart` together with `@fastify/swagger`. This PR includes the function in the source code to avoid forcing the programmer to always have to open this documentation to see if anything has been changed. And we can be sure that no developer will ever check this again, where future bugfixes will not be fixed for them.
Also, the previous `type: file` has been changed to an `OpenAPI` compatible `type: string, format: binary`.
> Include `ajvFilePlugin` into source and follow OpenAPI convention.

- index.js
- test/multipart-empty-body.test.js
We encountered `500` errors when `attachFieldsToBody` is set to `keyValues` and an empty body is submitted.
* There's already a test case which covers this scenario for `attachFieldsToBody` set to `true`
* Fixing this for `attachFieldsToBody` set to `keyValues` as well, and extend existing test
`test/big.test.js` fails for me locally, but it was failing before my changes already.
> fix: Empty body handling when attachFieldsToBody is keyValues

- index.js
- test/multipart-attach-body.test.js
---
Hey! This PR fixes #369
Seems like `_buf` is initialized with `null` and its data is being loaded through `part.toBuffer()`. The condition that checks if the field has data in its buffer compares only against `undefined` instead of `null`, leading to an exception when calling `field._buf.toString()` when `_buf === null`.
Let me know if I'm missing something or if something needs to be changed.
> Fix file stream consumption when buffer has not loaded yet

- index.js
- test/multipart-fileLimit.test.js
From the comments in the file, `options` contains instance level configuration and `opts` contains per-request overrides. Hence the above conditional statement doesn't respect per-request override. 
Fix: `options` should be replaced with `opts`.
Regression introduced in commit c47f60a8483c8238f7db448473b35bcfce33ab2b.
> Fix: throwFileSizeLimit value respects per-request override

- .github/workflows/ci.yml
- package.json
Per https://github.com/fastify/fastify-sensible/pull/138#discussion_r1276157318
To keep things consistent, this PR moves linting to the CI
> move linting to CI

- .taprc
- README.md
- index.js
- package.json
- test/multipart-attach-body.test.js
Carries over the work of https://github.com/fastify/fastify-multipart/pull/456
Closes #447
> Return buffers directly when `attachFieldsToBody` is set to `'keyValues'`

- .eslintrc.json
- tsconfig.eslint.json
I'm getting the following error in every JS file's first line:
```shell
Parsing error: ESLint was configured to run on `<tsconfigRootDir>/index.js` using `parserOptions.project`: .../fastify-multipart/tsconfig.eslint.json
However, that TSConfig does not include this file.
```
As a result no actual static checking happens
This PR simplifies the config and fixes that issue
> fix eslint

- index.js
- test/multipart-security.test.js
It's 36% faster and provides clearer intent
[Benchmark](https://perf.link/#eyJpZCI6ImwzcnoxZnRxNWxwIiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IHRlc3QgPSB7fSIsInRlc3RzIjpbeyJuYW1lIjoiRmluZCBpdGVtIDEwMCIsImNvZGUiOiJjb25zdCBhID0gXCJ0b1N0cmluZ1wiXG5pZighKGEgaW4gT2JqZWN0LnByb3RvdHlwZSkpIHRlc3RbYV0gPSAnU0FGRSciLCJydW5zIjpbMzc0NDAwMCw1MjcyMDAwLDQxMTAwMCwyNzcyMDAwLDEzMTQwMDAsMjgyODAwMCwxMDY0NTAwMCwxMjgwNzAwMCwxMzE0MDAwLDUwMDAwLDIzMDQwMDAsMTYzNjAwMCwxMTA0MzAwMCwxOTM1OTAwMCwzMjQ3MDAwLDY3MzMwMDAsMTY3MDgwMDAsMTMxNDAwMCw1ODk5MDAwLDE3NDcwMDAsMTIzMTUwMDAsMTM2NDEwMDAsMTY0NDIwMDAsMTQ5NjAwMCw4MTYxMDAwLDI3MDMwMDAsOTE1MjAwMCwxMzY0NDAwMCwyMTAzMzAwMCwzNDkwMDAwLDEyOTQwMDAwLDEwODUxMDAwLDE3Mzk5MDAwLDI0MDgwMDAsMTA1OTcwMDAsMzQ3ODAwMCwxODQzNDAwMCwzNjk0MDAwLDI3OTIwMDAsODg3OTAwM …
> use `in` to check for prototype violation

- index.js
Since we are using a Symbol to mark the request as multipart, I can't see a reason not to do this under `fastify.req` where we can decorate the object in advance and potentially get a performance improvement
> perf: do not mutate req.raw
