.travis.yml
README.md
index.js
package.json
test.js

Fixes #5.
Includes #4 
cc @mancioshell

Adds support for fields

---

README.md

added missing instantiation

---

README.md
example.js
form.html
index.js
package.json
test.js
tester.js

Fixes https://github.com/fastify/fastify-multipart/issues/19

Switch to busboy

---

index.js
package.json

- updates to fastify@0.39 #25
- adds name property to plugin-meta. see: https://github.com/fastify/fastify-plugin/issues/17#issuecomment-355972265

Updates fastify, plugin-meta

---

index.js
package.json
test.js

Fixes https://github.com/fastify/fastify-multipart/issues/29
@alizahid can you check if this fixes your issue?

do not abort the outgoing response

---

index.js
test/append-body.test.js

fix: all multipart request

---

index.d.ts
package.json
test/types/.eslintrc.json
test/types/index.ts

The body parameter was missing in the onFile type.
I set the type as object since I was not sure what to use, if you have a better idea, let me know.

add body to onFile in type definition file

---

.travis.yml
package.json

Greenkeeper/@types/node 12.0.6

---

index.js
test/multipart.test.js

Fixes #82 
Solution provided by https://github.com/mscdex/busboy/issues/140#issuecomment-282794446
It prevents Fastify from crashing on bad input and allows the developer to handle busboy constructor exceptions in Fastify's errorHandler.

Fix crash on bad input

---

package.json

chore(package): update eslint to version 6.6.0

---

index.d.ts
test/types/index.ts

fix: add missing options parameter to typings

---

README.md
index.js
test/append-body.test.js
test/multipart.test.js

Handle string arrays

---

index.js
package.json

Update to fastify v3-rc.3 and fix `addContentTypeParser` to newer format.

Fix content type parser format.

---

README.md

changes 'othwise' to 'otherwise'

fixes a typo in Readme.md

---

index.js
test/multipart-disk.test.js

Fixes https://github.com/fastify/fastify-multipart/issues/158

Reset tmpUploads at every request

---

README.md
examples/example.js
package.json

add install instruction for ts types

---

.github/workflows/ci.yml

chore: use fastify/github-action-merge-dependabot

---

test/multipart-small-stream.test.js

Make test not flaky

---

index.d.ts
test/index.test-d.ts

Fix incorrect error types

---

README.md

Updated limits example in docs

---

test/index.test-d.ts

This PR fixes a typo.
`Mulipart` -> `Multipart`

chore: fix typo Mulipart -> Multipart

---

README.md

docs: fix a link to Hooks.md

---

package.json

remove typescript dependency

---

index.js
package.json
test/multipart-attach-body.test.js

closes https://github.com/fastify/fastify-multipart/pull/359

fix: upload with same field name

---

index.js

remove intermediate variable

---

README.md

chore: fix typo on code example

---

package.json

move unused packages to devDependencies
